version: '2'
services:
    apitest-app:
        image: apitest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://apitest-postgresql:5432/apiTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    apitest-postgresql:
        extends:
            file: postgresql.yml
            service: apitest-postgresql
